name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 31.128.37.35 >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: |
          scp -o StrictHostKeyChecking=no -r target/coze-microservice-0.0.1-SNAPSHOT.jar root@31.128.37.35:/var/iiservice

      - name: Restart application
        run: ssh -o StrictHostKeyChecking=no root@31.128.37.35 'pkill -f "java -jar" || true && cd /var/iiservice && nohup java -jar coze-microservice-0.0.1-SNAPSHOT.jar --server.port=8080 > /dev/null 2>&1 &'