name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify build output
        run: ls -la target

      - name: Copy files via SCP
        run: |
          scp -o StrictHostKeyChecking=no target/coze-microservice-0.0.1-SNAPSHOT.jar root@31.128.37.35:/var/iiservice

      - name: Restart application
        env:
          SERVER_PORT: 8080
        run: ssh -o StrictHostKeyChecking=no root@31.128.37.35 'pkill -f "java -jar" || true && cd /var/iiservice && nohup java -jar coze-microservice-0.0.1-SNAPSHOT.jar --server.port=$SERVER_PORT > /dev/null 2>&1 &'